
Brainloom.add("biology", "easy", [
["What is the basic unit of life?","Cell","Tissue","Organ","Atom"],
["Which organ pumps blood around the body?","Heart","Liver","Lung","Kidney"],
["Which organ is mainly responsible for breathing?","Lungs","Stomach","Brain","Pancreas"],
["What substance carries oxygen in red blood cells?","Hemoglobin","Insulin","Keratin","Collagen"],
["Which part of a plant absorbs most water from soil?","Roots","Flowers","Fruits","Seeds"],
["What gas do plants take in during photosynthesis?","Carbon dioxide","Oxygen","Nitrogen","Hydrogen"],
["What gas is released during photosynthesis?","Oxygen","Carbon dioxide","Nitrogen","Methane"],
["Which organ controls most body activities?","Brain","Heart","Liver","Skin"],
["Which blood cells help fight infections?","White blood cells","Red blood cells","Platelets","Plasma"],
["Which blood cells carry oxygen?","Red blood cells","White blood cells","Platelets","Plasma"],
["What is the largest organ of the human body?","Skin","Liver","Lung","Brain"],
["Which organ helps digest food by producing bile?","Liver","Heart","Kidney","Lung"],
["Where does most digestion and nutrient absorption occur?","Small intestine","Large intestine","Esophagus","Stomach"],
["Which organ stores urine?","Bladder","Kidney","Liver","Stomach"],
["Which organs filter waste from blood to make urine?","Kidneys","Lungs","Liver","Heart"],
["What is the green pigment in plants called?","Chlorophyll","Melanin","Hemoglobin","Keratin"],
["What process do plants use to make food?","Photosynthesis","Respiration","Digestion","Excretion"],
["What is the male reproductive cell called?","Sperm","Egg","Zygote","Embryo"],
["What is the female reproductive cell called?","Egg","Sperm","Zygote","Pollen"],
["What do we call the joining of sperm and egg?","Fertilization","Respiration","Germination","Digestion"],
["What does a seed develop into under suitable conditions?","A plant","A mineral","A fungus","A virus"],
["Which part of a flower produces pollen?","Anther","Stigma","Ovary","Sepal"],
["Which part of a flower receives pollen?","Stigma","Anther","Petal","Filament"],
["Which organ helps humans exchange oxygen and carbon dioxide?","Lungs","Kidneys","Liver","Pancreas"],
["Which muscle helps the lungs expand during breathing?","Diaphragm","Biceps","Triceps","Deltoid"],
["How many chambers does the human heart have?","Four","Two","Three","Five"],
["Which mineral is important for strong bones and teeth?","Calcium","Sodium","Iron","Iodine"],
["Which vitamin is produced in skin with sunlight exposure?","Vitamin D","Vitamin C","Vitamin B12","Vitamin K"],
["Which nutrient is mainly used for growth and repair of tissues?","Protein","Water","Fiber","Salt"],
["Which nutrient is the body's main quick source of energy?","Carbohydrates","Proteins","Vitamins","Minerals"],
["What is the process of releasing energy from food in cells?","Cellular respiration","Photosynthesis","Transpiration","Pollination"],
["Which cell structure contains genetic material in most eukaryotic cells?","Nucleus","Cell wall","Vacuole","Ribosome"],
["Which structure controls what enters and leaves a cell?","Cell membrane","Cell wall","Nucleus","Chloroplast"],
["Which structure is found in plant cells but not animal cells?","Cell wall","Centrosome","Lysosome","Centriole"],
["Which organelle performs photosynthesis?","Chloroplast","Mitochondrion","Ribosome","Nucleus"],
["Which organelle is often called the powerhouse of the cell?","Mitochondrion","Nucleus","Golgi apparatus","Vacuole"],
["Which organelle makes proteins?","Ribosome","Lysosome","Vacuole","Chloroplast"],
["What is a group of similar cells performing a function called?","Tissue","Organ","System","Organism"],
["What is a group of organs working together called?","Organ system","Tissue","Cell","Chromosome"],
["Which body system carries blood?","Circulatory system","Digestive system","Skeletal system","Nervous system"],
["Which system breaks food into nutrients?","Digestive system","Respiratory system","Skeletal system","Endocrine system"],
["Which system sends electrical signals through the body?","Nervous system","Digestive system","Circulatory system","Skeletal system"],
["Which system supports and protects the body?","Skeletal system","Digestive system","Respiratory system","Urinary system"],
["What is the body's outer protective covering?","Skin","Muscle","Bone","Cartilage"],
["What do we call animals that eat only plants?","Herbivores","Carnivores","Omnivores","Decomposers"],
["What do we call animals that eat mainly other animals?","Carnivores","Herbivores","Producers","Parasites"],
["What do we call animals that eat both plants and animals?","Omnivores","Herbivores","Carnivores","Producers"],
["What organisms break down dead organic matter?","Decomposers","Producers","Predators","Herbivores"],
["What is an organism that makes its own food called?","Producer","Consumer","Decomposer","Parasite"],
["What is an organism that gets energy by eating other organisms called?","Consumer","Producer","Autotroph","Decomposer"],
["What is a habitat?","The place where an organism lives","A type of cell","A body organ","A food molecule"],
["What is biodiversity?","Variety of living organisms","Amount of rainfall","Size of a habitat","Number of rocks"],
["Which group includes bacteria?","Prokaryotes","Plants","Animals","Fungi"],
["Which organisms are usually microscopic and lack a nucleus?","Bacteria","Animals","Plants","Mushrooms"],
["Are viruses generally considered living cells?","No","Yes","Only in plants","Only in water"],
["What causes many infectious diseases?","Pathogens","Vitamins","Minerals","Hormones"],
["Which microorganism is used to make bread rise?","Yeast","Algae","Amoeba","Virus"],
["What type of organism is a mushroom?","Fungus","Plant","Animal","Bacterium"],
["What is the study of plants called?","Botany","Zoology","Ecology","Anatomy"],
["What is the study of animals called?","Zoology","Botany","Genetics","Mycology"],
["What is the study of heredity called?","Genetics","Ecology","Anatomy","Taxonomy"],
["What is the study of organisms and their environment called?","Ecology","Genetics","Histology","Embryology"],
["What is the scientific study of cells called?","Cell biology","Geology","Astronomy","Meteorology"],
["What is the process by which plants lose water vapor?","Transpiration","Digestion","Fertilization","Germination"],
["What is seed sprouting called?","Germination","Pollination","Respiration","Transpiration"],
["What is the transfer of pollen to a flower's stigma called?","Pollination","Fertilization","Germination","Respiration"],
["Which part of a plant usually anchors it in soil?","Root","Leaf","Flower","Fruit"],
["Which plant structure is mainly responsible for photosynthesis?","Leaf","Root","Flower","Seed"],
["Which structure protects a developing plant embryo?","Seed","Leaf","Root hair","Stem"],
["What carries water upward in plants?","Xylem","Phloem","Stomata","Petals"],
["What carries sugars through plants?","Phloem","Xylem","Stomata","Sepals"],
["Tiny openings on leaves used for gas exchange are called?","Stomata","Villi","Nephrons","Alveoli"],
["What is the smallest blood vessel?","Capillary","Artery","Vein","Aorta"],
["Which vessels carry blood away from the heart?","Arteries","Veins","Capillaries","Nerves"],
["Which vessels usually carry blood toward the heart?","Veins","Arteries","Capillaries","Bronchi"],
["What is the liquid part of blood called?","Plasma","Lymph","Bile","Mucus"],
["What helps blood clot?","Platelets","Red blood cells","Neurons","Alveoli"],
["What is the basic functional unit of the nervous system?","Neuron","Nephron","Alveolus","Platelet"],
["What is the basic functional unit of the kidney?","Nephron","Neuron","Alveolus","Villus"],
["What are the tiny air sacs in lungs called?","Alveoli","Nephrons","Villi","Neurons"],
["What are the finger-like structures that increase intestinal absorption?","Villi","Alveoli","Stomata","Nephrons"],
["Which organ produces insulin?","Pancreas","Liver","Kidney","Stomach"],
["Which hormone helps lower blood glucose?","Insulin","Adrenaline","Thyroxine","Estrogen"],
["Which gland is often called the master gland?","Pituitary gland","Thyroid gland","Adrenal gland","Pineal gland"],
["Which hormone is associated with the fight-or-flight response?","Adrenaline","Insulin","Melatonin","Insulin-like growth factor"],
["Which sense organ detects light?","Eye","Ear","Nose","Tongue"],
["Which part of the eye detects light?","Retina","Cornea","Iris","Lens"],
["Which organ is responsible for hearing and balance?","Ear","Eye","Nose","Skin"],
["Which sense detects chemicals in food?","Taste","Vision","Hearing","Balance"],
["Which organ detects smell?","Nose","Ear","Eye","Skin"],
["What is the hard tissue that forms the skeleton?","Bone","Muscle","Nerve","Blood"],
["What tissue contracts to produce movement?","Muscle","Bone","Cartilage","Epithelium"],
["What connects muscle to bone?","Tendon","Ligament","Cartilage","Nerve"],
["What connects bone to bone?","Ligament","Tendon","Muscle","Skin"],
["What protects the brain?","Skull","Rib cage","Pelvis","Femur"],
["What protects the heart and lungs?","Rib cage","Skull","Pelvis","Spine"],
["What is the longest bone in the human body?","Femur","Tibia","Humerus","Radius"],
["What is the process by which organisms produce offspring?","Reproduction","Respiration","Digestion","Excretion"],
["What is adaptation?","A trait that helps an organism survive","A type of disease","A cell organelle","A digestive enzyme"],
["What is evolution?","Change in populations over generations","Growth of one individual","Daily exercise","Cell digestion"],
["What is a species?","A group of organisms capable of producing fertile offspring","Any group of cells","A food chain","A type of tissue"],
["What is an ecosystem?","Organisms and their physical environment","Only animals in an area","Only plants in an area","A single organism"],
]);


Brainloom.add("biology", "normal", [
["Which organelle modifies, sorts, and packages proteins?","Golgi apparatus","Ribosome","Nucleus","Chloroplast"],
["Which organelle is mainly responsible for aerobic ATP production?","Mitochondrion","Lysosome","Golgi apparatus","Vacuole"],
["What molecule stores hereditary information?","DNA","ATP","Glucose","Lipid"],
["What is the shape of a typical DNA molecule?","Double helix","Single ring","Triple helix","Flat sheet"],
["What are DNA's building blocks called?","Nucleotides","Amino acids","Fatty acids","Monosaccharides"],
["Which base pairs with adenine in DNA?","Thymine","Cytosine","Guanine","Uracil"],
["Which base pairs with guanine?","Cytosine","Thymine","Adenine","Uracil"],
["What sugar is found in DNA?","Deoxyribose","Ribose","Glucose","Fructose"],
["What sugar is found in RNA?","Ribose","Deoxyribose","Glucose","Galactose"],
["Which base is found in RNA instead of thymine?","Uracil","Cytosine","Guanine","Adenine"],
["What process copies DNA before cell division?","DNA replication","Translation","Transcription","Glycolysis"],
["What process produces RNA from a DNA template?","Transcription","Translation","Replication","Fermentation"],
["What process uses mRNA to make a protein?","Translation","Transcription","Replication","Diffusion"],
["Where does transcription occur in eukaryotic cells?","Nucleus","Ribosome","Golgi apparatus","Mitochondrial matrix"],
["Where does translation occur?","Ribosomes","Nucleus","Lysosomes","Chloroplast membranes"],
["What carries amino acids to ribosomes?","tRNA","mRNA","rRNA","DNA"],
["What carries genetic instructions from DNA to ribosomes?","mRNA","tRNA","rRNA","ATP"],
["What is a codon?","A three-base sequence on mRNA","A three-base sequence on DNA only","A protein","A lipid"],
["What molecule provides much of the immediate energy for cellular work?","ATP","DNA","RNA","Cellulose"],
["Where does glycolysis occur?","Cytoplasm","Nucleus","Golgi apparatus","Lysosome"],
["What is the main product of glycolysis?","Pyruvate","Oxygen","DNA","Urea"],
["What molecule accepts electrons at the end of aerobic respiration?","Oxygen","Carbon dioxide","Glucose","Nitrogen"],
["What is fermentation used for when oxygen is limited?","Regenerating NAD+","Making DNA","Destroying ribosomes","Producing oxygen"],
["What is osmosis?","Movement of water across a selectively permeable membrane","Movement of proteins","Movement of DNA","Breakdown of glucose"],
["What is diffusion?","Movement from higher to lower concentration","Movement from lower to higher concentration using ATP","DNA replication","Protein synthesis"],
["What type of transport requires cellular energy?","Active transport","Simple diffusion","Osmosis","Facilitated diffusion"],
["What are enzymes?","Biological catalysts","Carbohydrates only","Genetic materials","Cell membranes"],
["What can high temperature do to many enzymes?","Denature them","Turn them into DNA","Increase their size permanently","Convert them to lipids"],
["What is an enzyme's active site?","Region where substrate binds","The enzyme's nucleus","A DNA segment","A membrane channel"],
["What is homeostasis?","Maintaining relatively stable internal conditions","Rapid growth","Cell division","Evolution"],
["Which blood component is important for immune defense?","White blood cells","Red blood cells","Platelets","Plasma proteins only"],
["What is an antibody?","A protein involved in specific immune recognition","A digestive enzyme","A red blood cell","A steroid hormone"],
["What type of immunity develops after vaccination?","Active acquired immunity","Passive immunity only","No immunity","Innate immunity only"],
["What is inflammation?","An immune response to injury or infection","A type of cell division","A digestive process","A genetic mutation"],
["What is the role of stomach acid?","Helps digestion and kills many microbes","Produces insulin","Filters blood","Carries oxygen"],
["Which enzyme begins protein digestion in the stomach?","Pepsin","Amylase","Lipase","Lactase"],
["Which enzyme breaks down starch?","Amylase","Pepsin","Lipase","Trypsin"],
["Which enzyme digests fats?","Lipase","Amylase","Pepsin","Lactase"],
["What is bile's main digestive role?","Emulsifies fats","Digests proteins directly","Breaks DNA","Absorbs glucose"],
["Where is bile stored?","Gallbladder","Pancreas","Kidney","Spleen"],
["Which organ produces many digestive enzymes?","Pancreas","Heart","Lung","Bladder"],
["What is the main function of the large intestine?","Absorb water and form feces","Absorb most amino acids","Produce insulin","Pump blood"],
["What is the functional unit of gas exchange in the lungs?","Alveolus","Bronchus","Trachea","Diaphragm"],
["How does oxygen enter the blood from alveoli?","Diffusion","Active transport","Endocytosis","Filtration"],
["What is the main function of hemoglobin?","Bind and transport oxygen","Digest proteins","Clot blood","Produce antibodies"],
["Which molecule causes red blood cells to carry oxygen efficiently?","Hemoglobin","Collagen","Keratin","Insulin"],
["What is the body's largest artery?","Aorta","Vena cava","Pulmonary vein","Carotid vein"],
["What is the pulmonary artery unusual for?","It carries deoxygenated blood away from the heart","It carries oxygenated blood to the body","It carries food","It carries urine"],
["What is the pulmonary vein unusual for?","It carries oxygenated blood to the heart","It carries deoxygenated blood to the lungs","It carries lymph","It carries bile"],
["What is the sinoatrial node?","The heart's natural pacemaker","A kidney structure","A brain region","A lung structure"],
["What is a synapse?","A junction between neurons or a neuron and target cell","A type of blood vessel","A muscle fiber","A bone joint"],
["What chemical messenger crosses many synapses?","Neurotransmitter","Hemoglobin","Bile","Insulin only"],
["What is a reflex?","A rapid automatic response","A slow learned habit only","A digestive enzyme","A hormone"],
["Which brain region helps coordinate balance and movement?","Cerebellum","Medulla","Hypothalamus","Pituitary"],
["Which brain region helps regulate body temperature and hunger?","Hypothalamus","Cerebellum","Occipital lobe","Spinal cord"],
["Which lobe is mainly associated with vision?","Occipital lobe","Frontal lobe","Temporal lobe","Parietal lobe"],
["Which lobe is strongly involved in hearing?","Temporal lobe","Occipital lobe","Frontal lobe","Parietal lobe"],
["What is a hormone?","A chemical messenger released by endocrine tissue","A type of bone","A blood cell","A digestive organ"],
["Which gland produces thyroxine?","Thyroid gland","Pancreas","Adrenal gland","Pituitary gland"],
["What does thyroxine mainly influence?","Metabolic rate","Blood clotting","Vision","Bone shape"],
["Which hormone raises blood glucose?","Glucagon","Insulin","Melatonin","Calcitonin"],
["Which hormone is produced by the adrenal medulla?","Adrenaline","Insulin","Thyroxine","Estrogen"],
["What is negative feedback?","A response that reduces the original change","A response that always increases change","DNA replication","Cell death"],
["What happens during mitosis?","One cell produces two genetically similar daughter cells","Gametes fuse","DNA is translated","Proteins are digested"],
["What is the main purpose of meiosis?","Producing haploid gametes","Repairing skin only","Producing identical body cells","Making ATP"],
["How many daughter cells result from one completed meiosis?","Four","Two","Three","Eight"],
["What is the chromosome number of human somatic cells?","46","23","44","92"],
["What is the chromosome number of human gametes?","23","46","22","92"],
["What is crossing over?","Exchange of DNA between homologous chromosomes","DNA replication","RNA translation","Cell membrane transport"],
["During which stage does crossing over occur?","Prophase I","Metaphase II","Anaphase II","Telophase I"],
["What are homologous chromosomes?","Chromosome pairs carrying the same types of genes","Identical copies formed in mitosis","RNA molecules","Sex hormones"],
["What is an allele?","A version of a gene","A whole chromosome","A protein organelle","A cell membrane"],
["What is a genotype?","An organism's genetic makeup","Its visible trait only","Its habitat","Its age"],
["What is a phenotype?","Observable characteristics","DNA sequence only","Chromosome number only","A type of gamete"],
["What is a dominant allele?","An allele expressed in a heterozygote","An allele always more common","An allele found only in males","An allele that cannot mutate"],
["What is a recessive allele?","An allele masked by a dominant allele in a heterozygote","An allele that never appears","An allele found only in plants","An allele that destroys DNA"],
["What does heterozygous mean?","Having two different alleles","Having two identical alleles","Having no alleles","Having three chromosomes"],
["What does homozygous mean?","Having two identical alleles","Having two different alleles","Having one chromosome","Having no genes"],
["What is a mutation?","A change in genetic material","A type of tissue","A digestive process","A hormone"],
["Can mutations be beneficial?","Yes","No","Only in bacteria","Only in plants"],
["What is natural selection?","Differential survival and reproduction of heritable variants","Random growth of cells","Intentional breeding by humans","DNA translation"],
["What is an adaptation?","A heritable feature that can improve survival or reproduction","Any temporary injury","A learned school skill","A cell organelle"],
["What is a food chain?","A sequence showing energy transfer through feeding","A DNA sequence","A blood pathway","A digestive tract"],
["What is a food web?","A network of interconnected food chains","A single feeding relationship","A plant root system","A cell membrane"],
["What is a trophic level?","A feeding position in an ecosystem","A type of chromosome","A body organ","A soil layer only"],
["Why does energy decrease at higher trophic levels?","Much energy is lost as heat and metabolism","Energy is created at every level","Predators produce sunlight","Plants stop photosynthesis"],
["What is a population?","Members of one species in an area","All organisms on Earth","Only predators in an ecosystem","All cells in an organism"],
["What is a community?","Different populations living and interacting in an area","One species only","A single organism","Only plants"],
["What is a niche?","An organism's ecological role and resource use","Its DNA sequence","Its body temperature","Its chromosome number"],
["What is carrying capacity?","Maximum population size an environment can sustainably support","Number of species in a forest","Amount of DNA in a cell","Number of predators only"],
["What is mutualism?","Both species benefit","One benefits and one is harmed","Neither is affected","Both are harmed"],
["What is parasitism?","One benefits while the host is harmed","Both benefit","Neither benefits","Both are harmed equally"],
["What is commensalism?","One benefits and the other is largely unaffected","Both benefit","Both are harmed","Neither benefits"],
["What is ecological succession?","Gradual change in a community over time","Daily migration","Cell division","DNA mutation"],
["What is a limiting factor?","A factor that restricts population growth","A type of hormone","A cell organelle","A genetic code"],
["What is conservation biology concerned with?","Protecting biodiversity and ecosystems","Increasing pollution","Producing artificial cells","Stopping all evolution"],
["What is taxonomy?","Classification and naming of organisms","Study of cells only","Study of weather","Study of rocks"],
["What is binomial nomenclature?","Two-part scientific naming system","A method of cell division","A blood typing system","A food chain"],
["What are bacteria that convert atmospheric nitrogen into usable compounds often called?","Nitrogen-fixing bacteria","Predators","Decomposers only","Viruses"],
["What is a pathogen?","An organism or agent that can cause disease","A vitamin","A hormone","A normal body cell"],
["What is antibiotic resistance?","Ability of bacteria to survive an antibiotic that once affected them","Ability to make oxygen","Ability to digest fat","Resistance of viruses to sunlight"],
["Why don't antibiotics normally treat viruses?","Viruses lack the bacterial targets antibiotics are designed to attack","Viruses are too large","Viruses are plants","Antibiotics only work on fungi"],
["What is a vector in disease transmission?","An organism that carries a pathogen between hosts","A type of antibody","A digestive enzyme","A white blood cell"],
]);


Brainloom.add("biology", "hard", [
["Which enzyme unwinds DNA during replication?","Helicase","Ligase","Polymerase","Primase"],
["Which enzyme adds nucleotides to a growing DNA strand?","DNA polymerase","Helicase","Ligase","Topoisomerase"],
["Which enzyme joins Okazaki fragments?","DNA ligase","Helicase","Primase","RNA polymerase"],
["What are Okazaki fragments?","Short DNA fragments formed on the lagging strand","RNA molecules","Proteins made by ribosomes","Chromosome pairs"],
["Why is one DNA strand synthesized discontinuously?","DNA polymerase works only in the 5' to 3' direction","DNA lacks nucleotides","Helicase blocks the strand","Ribosomes stop replication"],
["What is the function of primase?","Synthesizes RNA primers","Unwinds DNA","Joins DNA fragments","Removes introns"],
["What is a promoter?","A DNA region where transcription machinery binds","A protein-folding site","An RNA enzyme","A chromosome end"],
["What is an intron?","A noncoding region removed from pre-mRNA","A protein-coding ribosome","A DNA polymerase","A chromosome cap"],
["What is an exon?","A region retained in mature RNA after splicing","A DNA-digesting enzyme","A lipid","A chromosome centromere"],
["What is alternative splicing?","Producing different RNA transcripts from the same pre-mRNA","Copying DNA twice","Making ATP without oxygen","Breaking down glucose"],
["What is a transcription factor?","A protein that regulates transcription","A carbohydrate","A ribosome subunit only","A DNA nucleotide"],
["What is an operon?","A cluster of genes regulated together, common in bacteria","A human chromosome","A cell organelle","A type of lipid"],
["What is the lac operon associated with?","Regulation of lactose metabolism in bacteria","DNA replication in humans","Photosynthesis","Blood clotting"],
["What is epigenetics?","Heritable changes in gene expression without changing DNA sequence","Mutation of every gene","Protein digestion","Chromosome duplication only"],
["What is DNA methylation often associated with?","Reduced gene expression","Increased ATP production","Protein digestion","Cell membrane formation"],
["What is a point mutation?","A change involving a single nucleotide","A change involving every chromosome","A whole-cell mutation","A tissue injury"],
["What is a missense mutation?","A nucleotide change that alters an encoded amino acid","A mutation that always stops translation","A mutation with no DNA change","A chromosome loss"],
["What is a nonsense mutation?","A mutation that creates a premature stop codon","A mutation that changes one amino acid only","A mutation that duplicates a chromosome","A mutation in RNA only"],
["What is a frameshift mutation?","An insertion or deletion that changes the reading frame","A change in one protein bond","A chromosome crossing over","A silent substitution"],
["What is a silent mutation?","A mutation that does not change the encoded amino acid","A mutation that destroys a chromosome","A mutation that stops all transcription","A mutation that always causes disease"],
["What is the genetic code described as degenerate?","Multiple codons can encode the same amino acid","Every codon encodes several proteins","DNA has no codons","Every amino acid has one codon"],
["What is a start codon?","A codon that initiates translation","A codon that stops transcription","A DNA primer","A protein"],
["Which is the common start codon?","AUG","UAA","UGA","UAG"],
["Which codons are stop codons?","UAA, UAG, UGA","AUG, UGG, UUU","AAA, CCC, GGG","GCU, GCC, GCA"],
["What is post-translational modification?","Chemical modification of a protein after translation","DNA replication after mitosis","RNA copying DNA","Cell division"],
["What is protein denaturation?","Loss of a protein's normal structure and function","DNA replication","RNA transcription","Cell fusion"],
["What is an allosteric enzyme?","An enzyme regulated by binding at a site other than the active site","An enzyme without a substrate","A DNA molecule","A ribosome"],
["What is competitive inhibition?","An inhibitor competes with substrate for the active site","An inhibitor destroys DNA","An inhibitor increases substrate binding","An inhibitor permanently removes an enzyme"],
["What happens to competitive inhibition when substrate concentration increases greatly?","Its effect can often be reduced","It always becomes irreversible","The enzyme disappears","ATP production stops"],
["What is noncompetitive inhibition?","Inhibition through binding away from the active site that reduces enzyme activity","Substrate binding to the active site","DNA replication","RNA splicing"],
["What is the Michaelis constant Km commonly used to describe?","Substrate concentration at half Vmax","Maximum chromosome number","Cell volume","ATP concentration only"],
["What does Vmax represent?","Maximum reaction velocity under given conditions","Minimum enzyme concentration","DNA length","Cell size"],
["What is oxidative phosphorylation?","ATP production driven by an electron transport chain and chemiosmosis","Glucose splitting only","DNA replication","Protein folding"],
["Where is the electron transport chain located in mitochondria?","Inner mitochondrial membrane","Outer membrane","Matrix only","Nucleus"],
["What creates the proton gradient used by ATP synthase?","Electron transport chain","Ribosomes","DNA polymerase","Golgi apparatus"],
["What is chemiosmosis?","Movement of ions down an electrochemical gradient to drive ATP synthesis","Movement of DNA into the nucleus","Protein digestion","Cell division"],
["What is the final electron acceptor in aerobic respiration?","Oxygen","Glucose","Carbon dioxide","NADH"],
["What is the main product of the Krebs cycle per acetyl-CoA that carries high-energy electrons?","NADH and FADH2","DNA","Oxygen","Cellulose"],
["Where does the Krebs cycle occur in eukaryotic cells?","Mitochondrial matrix","Cytoplasm","Nucleus","Golgi apparatus"],
["What is substrate-level phosphorylation?","Direct formation of ATP by transferring a phosphate to ADP","ATP formation by DNA","Protein synthesis","Oxygen transport"],
["What is the Calvin cycle used for?","Carbon fixation in photosynthesis","Protein digestion","DNA repair","Nitrogen excretion"],
["Where does the Calvin cycle occur?","Chloroplast stroma","Thylakoid lumen","Mitochondrial matrix","Nucleus"],
["What is the primary carbon-fixing enzyme in the Calvin cycle?","RuBisCO","ATP synthase","DNA polymerase","Pepsin"],
["What is photophosphorylation?","Light-driven ATP production in photosynthesis","ATP production in glycolysis","DNA replication","Protein degradation"],
["What molecule donates electrons to replace those lost by photosystem II?","Water","Carbon dioxide","Glucose","NADPH"],
["What gas is released when water is split during photosynthesis?","Oxygen","Carbon dioxide","Nitrogen","Hydrogen sulfide"],
["What is the role of NADPH in the Calvin cycle?","Provides reducing power","Carries oxygen","Digests starch","Forms DNA"],
["What is photorespiration?","A process involving RuBisCO oxygenation that can reduce photosynthetic efficiency","A form of animal respiration","DNA repair","Protein synthesis"],
["Why are C4 plants adapted to hot environments?","They concentrate CO2 around RuBisCO and reduce photorespiration","They do not need sunlight","They lack chloroplasts","They cannot perform respiration"],
["What is CAM photosynthesis?","A pathway that takes in CO2 mainly at night to reduce water loss","A bacterial respiration pathway","A type of mitosis","An animal adaptation"],
["What is the sodium-potassium pump?","An ATP-powered membrane protein moving Na+ out and K+ in","A passive channel","A digestive enzyme","A DNA transporter"],
["What is membrane potential?","A voltage difference across a cell membrane","A difference in DNA sequences","A pressure in the nucleus","A protein concentration only"],
["What is an action potential?","A rapid change in membrane potential that propagates along an excitable cell","A hormone pulse only","A muscle protein","A blood clot"],
["What causes depolarization in a typical neuronal action potential?","Opening of voltage-gated sodium channels","Closing all sodium channels","Opening chloride pumps","ATP leaving the cell"],
["What causes repolarization after the peak of a neuronal action potential?","Potassium efflux through voltage-gated potassium channels","Sodium entering continuously","Calcium leaving the nucleus","Glucose uptake"],
["What is saltatory conduction?","Action potential propagation by jumping between nodes of Ranvier","Slow diffusion through blood","Signal transmission through hormones","DNA movement"],
["What are nodes of Ranvier?","Gaps between myelin segments on an axon","Neuron cell bodies","Synaptic vesicles","Brain ventricles"],
["What neurotransmitter is released at the neuromuscular junction of skeletal muscle?","Acetylcholine","Insulin","Dopamine","Thyroxine"],
["What is the role of calcium ions in skeletal muscle contraction?","They bind troponin and allow actin-myosin interaction","They digest ATP","They destroy actin","They block all movement"],
["What is the sliding filament model?","Actin and myosin slide past each other during contraction","Bones slide through cartilage","DNA strands slide during replication","Blood cells slide through arteries"],
["What is the functional unit of skeletal muscle contraction?","Sarcomere","Neuron","Nephron","Alveolus"],
["What protein forms the thin filament in skeletal muscle?","Actin","Myosin","Keratin","Collagen"],
["What protein forms the thick filament?","Myosin","Actin","Elastin","Tubulin"],
["What is the role of troponin?","It binds calcium and helps regulate muscle contraction","It transports oxygen","It digests proteins","It forms DNA"],
["What is glomerular filtration?","Filtration of blood plasma into the nephron","Reabsorption of glucose only","Urine storage","Hormone secretion"],
["What is the functional filtration barrier of the renal corpuscle?","Glomerular capillaries, basement membrane, and podocytes","Only collecting duct cells","Only the bladder wall","Only the ureter"],
["What is tubular reabsorption?","Movement of useful substances from filtrate back into blood","Movement of urine into the bladder only","Formation of red blood cells","Protein digestion"],
["What hormone increases water reabsorption in collecting ducts?","ADH","Insulin","Glucagon","Thyroxine"],
["What hormone promotes sodium reabsorption in the kidney?","Aldosterone","Melatonin","Insulin","Adrenaline"],
["What is countercurrent multiplication associated with?","Creating a medullary osmotic gradient in the kidney","Blood clotting","DNA replication","Muscle contraction"],
["What is the main nitrogenous waste excreted in human urine?","Urea","Glucose","Oxygen","Glycogen"],
["What is the role of the loop of Henle?","Helps establish the osmotic gradient used to concentrate urine","Produces bile","Pumps blood","Stores urine"],
["What is clonal selection?","Activation and proliferation of lymphocytes recognizing a specific antigen","Random mutation of all immune cells","Destruction of all antibodies","Formation of red blood cells"],
["What is an antigen?","A substance recognized by the adaptive immune system","A digestive enzyme","A red blood cell","A steroid"],
["What are helper T cells important for?","Coordinating immune responses through signaling","Producing hemoglobin","Digesting fats","Making bile"],
["What do cytotoxic T cells primarily do?","Kill infected or abnormal cells","Produce antibodies directly","Carry oxygen","Make insulin"],
["Which cells produce antibodies?","Plasma cells","Red blood cells","Platelets","Neurons"],
["What is immunological memory?","Long-lasting immune response based on memory cells","Permanent fever","Loss of antibodies","DNA replication in bacteria"],
["What is MHC?","A molecule system that presents peptide fragments to T cells","A digestive enzyme","A blood sugar","A hormone"],
["What is an autoimmune disease?","A condition in which the immune system attacks the body's own tissues","A bacterial infection only","A vitamin deficiency","A bone fracture"],
["What is apoptosis?","Programmed cell death","Uncontrolled cell growth","DNA replication","Protein synthesis"],
["Why is apoptosis important?","It removes unwanted or damaged cells in a controlled way","It always causes disease","It stops all immune responses","It produces glucose"],
["What is necrosis?","Cell death associated with loss of membrane integrity and tissue injury","Normal programmed cell death","DNA transcription","Protein folding"],
["What is a proto-oncogene?","A normal gene that can contribute to cancer when abnormally activated","A gene found only in viruses","A DNA repair enzyme","A chromosome cap"],
["What is a tumor suppressor gene?","A gene that helps restrain inappropriate cell growth","A gene that always causes cancer","A gene that makes glucose","A gene for oxygen transport"],
["What is angiogenesis?","Formation of new blood vessels","Formation of new neurons only","Formation of bone only","DNA replication"],
["What is metastasis?","Spread of cancer cells to distant sites","Formation of antibodies","Normal cell division","Blood clotting"],
["What is a stem cell?","A cell capable of self-renewal and differentiation","A mature red blood cell","A dead cell","A virus"],
["What is differentiation?","Process by which cells become specialized","Cell death only","DNA replication only","Protein digestion"],
["What is totipotency?","Ability to generate all cell types including extraembryonic tissues","Ability to form only muscle","Ability to form only blood","Ability to form only neurons"],
["What is pluripotency?","Ability to form many body cell types but not an entire organism alone","Ability to form only one tissue","Ability to make DNA only","Ability to produce hormones only"],
["What is horizontal gene transfer?","Transfer of genetic material between organisms outside parent-to-offspring inheritance","DNA replication in one cell","Protein synthesis","Cell division"],
["What is transformation in bacteria?","Uptake of free DNA from the environment","Transfer by a bacteriophage","Transfer by direct cell contact","Formation of spores"],
["What is transduction?","Bacteriophage-mediated transfer of bacterial DNA","DNA uptake from water","Direct bacterial mating","Protein synthesis"],
["What is conjugation?","Direct transfer of DNA between bacteria, often through a pilus","Viral infection only","DNA replication only","Cell respiration"],
["What is a plasmid?","A small usually circular DNA molecule separate from the bacterial chromosome","A protein capsule","A viral enzyme","A plant organ"],
["What is CRISPR-Cas technology commonly used for?","Targeted genome editing","Protein digestion","ATP production","Blood filtration"],
["What is PCR used for?","Amplifying specific DNA sequences","Producing ATP","Digesting proteins","Measuring blood pressure"],
["What does PCR require to define the target region?","Primers","Ribosomes","Antibodies","Lipids"],
["What is gel electrophoresis used to do with DNA fragments?","Separate them mainly by size","Translate them into proteins","Destroy them","Convert them into RNA"],
["What is genetic drift?","Random change in allele frequencies due to chance","Selection caused by environmental advantage","DNA replication","Protein folding"],
["What is the founder effect?","A new population established by a small subset of a larger population","A mutation caused by sunlight","Natural selection in a large population","Gene translation"],
["What is a bottleneck effect?","A sharp reduction in population size that changes allele frequencies","A rapid increase in biodiversity","A type of cell division","A protein mutation"],
["What is gene flow?","Movement of alleles between populations","Movement of ATP in cells","Movement of blood","Movement of RNA to ribosomes"],
["What is reproductive isolation?","Reduced gene flow between populations due to barriers to reproduction","Rapid cell division","DNA repair","Protein synthesis"],
["What is allopatric speciation?","Speciation caused by geographic isolation","Speciation without any population separation","A type of mutation","Cell differentiation"],
["What is convergent evolution?","Independent evolution of similar traits in different lineages","Evolution of one species into many due to isolation","Random DNA copying","Loss of all adaptations"],
["What is homologous structure?","A structure inherited from a common ancestor, potentially with different functions","A structure with no evolutionary relationship","A viral protein","A cell organelle"],
["What is analogous structure?","A structure with similar function but different evolutionary origin","A structure with identical DNA origin","A chromosome pair","A type of mutation"],
["What is phylogeny?","Evolutionary history and relationships among organisms","Study of individual cells","Study of digestion","Study of hormones"],
]);